posts/urls.py
from . import views
from django.conf.urls import url

app_name = 'posts'

urlpatterns = [
		url(r'^all/$', views.EventList.as_view(), name='all_event'),
		url(r'^(?P<pk>\d+)/$', views.EventDetail.as_view(), name='event_detail'),
		url(r'^del/(?P<pk>\d+)/$', views.DeleteEvent.as_view(), name='event_delete'),
		url(r'^drafts/$', views.draft_list, name='draft_list'),
		url(r'^article/(?P<pk>\d+)/publish/$', views.publish_event, name='publish_event'),
]

register/urls.py
from . import views
from django.conf.urls import url

app_name = 'register'

urlpatterns = [
		
		# /members/register/
		url(r'^register/$', views.member_register, name='register')
	]

speoau/urls.py
from django.conf import settings
from django.conf.urls.static import static

from filebrowser.sites import site
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
   	
    url(r'^admin/', admin.site.urls),
    url(r'^members/', include('register.urls')),
    url(r'^posts/', include('posts.urls')),

	url(r'^$', views.home, name='home'),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gallery/models.py
from django.db import models

# Create your models here.

posts/models.py
from __future__ import unicode_literals
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
import datetime
from django.core.urlresolvers import reverse
# Create your models here.


class Event(models.Model):
	event = models.CharField('title', max_length=100)
	event_date = models.DateField('date of event')
	summary = models.CharField(max_length=150, default='')
	event_desc = RichTextUploadingField('content')
	date_created = models.DateField(auto_now_add=True)
	post_date = models.DateField('date posted', blank=True, null=True)

	
	def __str__(self):
		return self.event

	def publish(self):
	    self.post_date = datetime.date.today()
	    self.save()

	def get_absolute_url(self):
		return reverse('posts:post_detail', kwargs={'pk':self.pk})

register/models.py
from django.db import models
import datetime
from django.core.urlresolvers import reverse

# Create your models here.

class Member(models.Model):

	LEVEL = (
		(1, 100),
		(2, 200),
		(3, 300),
		(4, 400),
		(5, 500),
		(6, 600),
		)
	
	GENDER = (
		('F', 'female'),
		('M', 'male')
		)

	DEPT = (
		('age', 'Agricultural Engineering'),
		('bch', 'Biochemistry'),		
		('che', 'Chemical Engineering'),
		('chm', 'Chemistry'),
		('cve', 'Civil Engineering'),
		('csc', 'Computer Engineering'),
		('eee', 'Elect. Elect. Engineering'),
		('geo', 'Geology'),
		('msc', 'Materials Science Engineering'),
		('mth', 'Mathematics'),
		('mee', 'Mechanical Engineering'),
		('phy', 'Physics'),
		)

	COMMITTEES = (
		('cty', 'Catch Them Young'),
		('com', 'Petro Bowl / Quiz'),
		('reg', 'Registration'),
	)


	fullname = models.CharField(max_length=30, default='')
	phone = models.CharField(max_length=11, blank=True)
	gender = models.CharField('sex', max_length=1, choices=GENDER)
	email = models.EmailField(max_length=30, unique=True)
	level = models.IntegerField(choices=LEVEL)
	dept = models.CharField('Department', max_length=3, choices=DEPT)
	reg_date = models.DateField('Date Registered', auto_now_add=True)
	alumni = models.BooleanField(default=False)
	committee = models.CharField(max_length=3, default='', choices=COMMITTEES)


	def __str__(self):
		"""Returns the fullname."""
		return self.fullname.strip()

	def get_short_name(self):
		"""Returns the short name for the user."""
		return self.first_name

	def get_absolute_url(self):
		return reverse('register:member_detail', kwargs={'pk':self.pk})

posts/forms.py
# from django import forms
# from .models import Event
# from tinymce.widgets import TinyMCE

# class EventForm(forms.ModelForm):

# 	event_desc = forms.CharField(widget=TinyMCE(attrs={'cols': 80, 'rows': 30}))

# 	widgets = {'event': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Title of the Event', 'id':'event'}),
# 		        'summary': forms.TextInput(attrs={'class':'form-control', 'placeholder':'A breif about the event in at most 30 words', 'id':'summary'}),
# 		        'event_date': forms.EmailInput(attrs={'class':'form-control', 'placeholder':'Date of the Event', 'id':'event_date'}),
# 		        'event_desc': forms.Select(attrs={'class':'form-control',})
#         }

# 	class Meta:
# 		model = Event
# 		fields = ['event', 'event_date', 'summary', 'event_desc']

register/forms.py
from django import forms
from .models import Member
from django.core.exceptions import ValidationError

class RegistrationForm(forms.ModelForm):
	class Meta:
		model = Member
		fields = ['fullname', 'level', 'phone','gender', 'email', 'dept']

		widgets = {'fullname': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Fullname', 'id':'fullname'}),
		          'phone': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Phone Number', 'id':'phone'}),
		          'email': forms.EmailInput(attrs={'class':'form-control', 'placeholder':'email', 'id':'email'}),
		          'dept': forms.Select(attrs={'class':'form-control', 'placeholder':'Select Your Department'}),
		          'gender': forms.Select(attrs={'class':'form-control', 'placeholder':'Select'}),
		          'level': forms.Select(attrs={'class':'form-control', 'placeholder':'Select'}),
        }


	def clean_email(self):
		email = self.cleaned_data['email']
		sth, prov = email.split("@")
		ext = ['yahoo.com', 'gmail.com']
		if (prov not in ext):
			raise forms.ValidationError('Please enter a gmail or yahoo mail address')
		return email

gallery/views.py
from django.shortcuts import render

# Create your views here.

posts/views.py
from .models import Event
from django.views.generic import ListView, DetailView
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic.edit import DeleteView, UpdateView
from django.conf import settings
import datetime
from django.shortcuts import get_object_or_404, redirect, render

# Create your views here.


class EventList(ListView):
	model = Event
	context_object_name = 'events'
	template_name = 'posts/events_list.html'

	def get_queryset(self):
		events = Event.objects.filter(post_date__isnull=False)
		return events.filter(event_date__gte=datetime.date.today()).order_by('event_date')


class EventDetail(DetailView):
	model = Event
	context_object_name = 'event'
	template_name = 'posts/event_detail.html'


def draft_list(request):
    events = Event.objects.filter(post_date__isnull=True).order_by('date_created')
    return render(request, 'posts/events_list.html', {'events': events})


@permission_required('event.add_event', login_url='/login')
def publish_event(request, pk):
    event = get_object_or_404(Event, pk=pk)
    event.publish()
    return redirect('event:all_events')


class DeleteEvent(PermissionRequiredMixin, DeleteView):
	model = Event
	success_url = reverse_lazy('event:draft_list')
	permission_required = 'event.delete_event'
	login_url='settings.LOGIN_URL'

register/views.py
from .models import Member
from django.shortcuts import render, redirect, get_object_or_404
import datetime
from .forms import RegistrationForm
from django.views.generic import View
# Create your views here.

def member_register(request):
	if request.method == 'POST':
		form = RegistrationForm(request.POST)
		if form.is_valid():
			user = form.save(commit=False)
			user.alumni = False
			user.date = datetime.date.today()
			user.save()
			return redirect('home')
	else:
		form = RegistrationForm()
	return render(request, 'register/register.html', { 'form': form })

speoau/views.py
from django.shortcuts import render
from register.models import Member
from posts.models import Event
from datetime import date
from django.contrib.auth.models import User


def home(request):
	user = User.objects.all()
	event_all = Event.objects.filter(post_date__isnull=False)
	events = event_all.filter(event_date__gte=date.today()).order_by('event_date')[:4]
	return render(request, 'home.html', {'events':events, 'user':user})

posts/templates/posts/event_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %} {{ event.event }} | speoau{% endblock %}

{% block banner %}{% endblock %}

{% block welcome %}{% endblock %}

{% block events %}
<div class="col-sm-12 col-md-9">
	<div class="title-tile">
    <h3 class="tile-header">{{ event.event }}</h3>
  </div>
  {% if user.is_authenticated %}
	  <ul>
      <li style="display:inline; float:right;"><a href="{% url 'posts:event_delete' event.pk %}" class="btn" data-toggle="tooltip" data-placement="bottom" title="Delete"><i style="font-size:20px" class="glyphicon glyphicon-trash"></i></a></li>
      <li style="display:inline; float:right;"><a href="{% url 'posts:publish_event' event.pk %}" class="btn" data-toggle="tooltip" data-placement="bottom" title="Publish"><i style="font-size:20px" class="glyphicon glyphicon-share"></i></a></li>
    </ul>
  {% endif %}
	<p style="font-family:Georgia; margin-top:10px; font-size:15px;"><strong>Date of Event: {{ event.event_date }}</strong></p>
	<p class="tile-text">{{ event.event_desc|safe }}</p>
</div>
{% endblock %}

{% block oil-watch %}{% endblock %}

{% block resources %}{% endblock %}

{% block gallery %}{% endblock %}

{% block vision %}{% endblock %}

posts/templates/posts/events_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %} events | speoau {% endblock %}

{% block custom %}{% static 'css/events.css' %}{% endblock %}


{% block banner %}{% endblock %}

{% block welcome %}{% endblock %}

{% block events %}
  <div class="col-s12 col-md-9" style="padding-left:0; padding-right:0;">
  <div class="title-tile">
    <h3 class="tile-header">Upcoming Events</h3>
  </div>
  {% for event in events %}
  <div class="header" style="padding: 0 20px;">
  	{% if user.is_authenticated %}
      {% if not event.post_date %}
  		  <ul>
  	      <li style="display:inline; float:right;"><a href="{% url 'posts:event_delete' event.pk %}" class="btn" data-toggle="tooltip" data-placement="bottom" title="Delete"><i style="font-size:20px" class="glyphicon glyphicon-trash"></i></a></li>
  	      <li style="display:inline; float:right;"><a href="{% url 'posts:publish_event' event.pk %}" class="btn" data-toggle="tooltip" data-placement="bottom" title="Publish"><i style="font-size:20px" class="glyphicon glyphicon-share"></i></a></li>
  	    </ul>
      {% endif %}
    {% endif %}
    <h4 class="tile-caption"><a href="{% url 'posts:event_detail' event.pk %}">{{ event.event|upper }}</a></h4>
  </div>
  <div class="events-body" style="padding: 0 20px;">
    <p class="event-date"><strong>Date of Event: {{event.event_date}}</strong></p>
    <p class="tile-text">{{ event.summary }}</p>
  </div>

  {% empty %}
  <p class="empty">There are no posts available yet</p>
  {% endfor %}
  </div>
{% endblock %}

	
{% block oil-watch %}{% endblock %}

{% block resources %}{% endblock %}

{% block gallery %}{% endblock %}

{% block vision %}{% endblock %}

register/templates/register/register.html
{% extends 'base.html' %}
{% load static %}

{% block title %} speoau | register {% endblock %}

{% block custom %}{% static 'css/register.css' %}{% endblock %}


{% block banner %}{% endblock %}

{% block left-side %} {% endblock %}

	
{% block forms %}

	<h1 class="form-header text-center">Registration Form</h1>

	<form method="POST" action="">{% csrf_token %}
		<div class="input-group  input-group-lg">
  	<span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
  	{{ form.fullname.errors }}
	  	{{ form.fullname }}
		  {% if form.help_text %}
				<p class="help">{{ form.help_text|safe }}</p>
		  {% endif %}
		</div>

		<div class="input-group  input-group-lg">
  	<span class="input-group-addon"><i class="glyphicon glyphicon-earphone"></i></span>
  	{{ form.phone.errors }}
	  	{{ form.phone }}
		  {% if form.help_text %}
				<p class="help">{{ form.help_text|safe }}</p>
		  {% endif %}
		</div>
		<div class="input-group  input-group-lg">
		<span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
  	{{ form.email.errors }}
	  	{{ form.email }}
		  {% if form.help_text %}
				<p class="help">{{ form.help_text|safe }}</p>
		  {% endif %}
		</div>
		<div class="input-group  input-group-lg">
		<span class="input-group-addon">Department</span>
  	{{ form.dept.errors }}
	  	{{ form.dept }}
		  {% if form.help_text %}
				<p class="help">{{ form.help_text|safe }}</p>
		  {% endif %}
		</div>
		<div class="input-group  input-group-lg">
		<span class="input-group-addon">Sex</span>
  	{{ form.gender.errors }}
	  	{{ form.gender }}
		  {% if form.help_text %}
				<p class="help">{{ form.help_text|safe }}</p>
		  {% endif %}
		</div>
		<div class="input-group  input-group-lg">
		<span class="input-group-addon">Level:</span>
  	{{ form.level.errors }}
	  	{{ form.level }}
		  {% if form.help_text %}
				<p class="help">{{ form.help_text|safe }}</p>
		  {% endif %}
		</div>

		<div class="bttn">
			<button type="submit" class="btn btn-lg btn-block">Submit</button>				
		</div>
	</form>

{% endblock %}


{% block welcome %}{% endblock %}
  
{% block resources %}{% endblock %}

{% block gallery %}{% endblock %}

{% block vision %}{% endblock %}

speoau/templates/base.html
<!DOCTYPE html>
<html>
<head>
  {% load static %}
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %} speoau | home {% endblock %}</title>
  
  <link href="https://fonts.googleapis.com/css?family=Oswald" rel="stylesheet">
  <!-- offline bootstrap -->
  <link href="{% static 'css/bootstrap.min.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <!-- Custom css -->
  <link rel="stylesheet" type="text/css" href="{% block base %}{% static 'css/base.css' %}{% endblock %}" >
  <link rel="stylesheet" type="text/css" href="{% block custom %} {% endblock %}" >
</head>
<body>
  <!--              Navbar 
  ================================================== 
  -->
  {% block navbar %}
  <div class="container navbar-container">
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">

      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#"><img src="{% static 'img/logo.png' %}"></a>
        <div class="chapter">
          <p class="chem">SPEOAU Student Chapter</p>
          <p class="oau">Obafemi Awolowo University</p>
        </div>
      </div>

      <div id="myNavbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="#">Home</a></li>
          <li><a href="{% url 'posts:all_event' %}">Events</a></li>
          <li><a href="#">Gallery</a></li>
          <li><a href="#resources">SPE Resources</a></li>
          <li><a href="{% url 'register:register' %}">Register</a></li>
        </ul>
      </div>
    </div>
  </nav>
  </div>
  {% endblock %}

  <div class="container container-wrapper">
    {% block banner %}
    <div class="banner">
      <div class="jumbotron spe-img">
        <img src="{% static 'img/speoau.jpg' %}">
      </div>
    </div>
    {% endblock %}

    <!--              Main Content 
    ================================================== 
    -->
    <div class="row">
      <div class="col-sm-12 col-md-3">
        {% block welcome %}
        <div class="tile-body" style="height:500px; margin-bottom:30px">
          <div class="title-tile">
            <h3 class="tile-header">Welcome</h3>
          </div>
          <img class="img-tile" src="{% static 'img/president.jpg' %}" alt="President's image" style="height:150px;">
          <h3 class="tile-caption text-center">Welcome Note</h3> 
          <p class="tile-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
          <p><a class="btn btn-default button tile-text" style="background-color:#3aa7a7" href="#" role="button">Continue &raquo;</a></p>
        </div>
        {% endblock %}
        
        {% block join-spe %}
        <div class="tile-body" style="height:500px;">
          <div class="title-tile">
            <a href="{% url 'register:register' %}"><h3 class="tile-header" style="background-color:#102c4e;">JOIN SPE</h3></a>
          </div>
          <img class="img-tile" src="{% static 'img/speoau.jpg' %}" alt="speoau image" style="height:150px;">
          <a href="{% url 'register:register' %}"><h3 class="tile-caption text-center">Why SPEOAU?</h3></a>
          <p class="tile-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
          <p><a class="btn btn-default button tile-text" style="background-color:#102c4e; margin-bottom:20px;" href="#" role="button">Continue &raquo;</a></p>
          {% endblock %}
        </div>
      </div>

      {% block events %}{% endblock %}

      {% block forms %}{% endblock %}

      {% block oil-watch %}
      <div class="col-sm-12 col-md-3 tile-body" style="margin-bottom:30px">
        <div class="title-tile">
          <h3 class="tile-header" style="background-color:#b90a0a">Oil Watch</h3>
        </div>
        <div style="padding:35px">
          <script type="text/javascript" src="https://www.oil-price.net/TABLE2/gen.php?lang=en"></script>
          <div class="padding"></div>
          <script type="text/javascript" src="https://www.oil-price.net/widgets/brent_crude_price_large/gen.php?lang=en"></script>
        </div>
      </div>
      {% endblock %}

      {% block resources %}
      <div class="col-sm-12 col-md-9 tile-body" style="margin-bottom:30px">
        <div class="title-tile">
          <h3 class="tile-header">SPE Resources</h3>
        </div>
        <div class="col-sm- col-md-4">
          <div class="padding"></div>
          <div class="resource">
            <a href="https://www.onepetro.org/?_ga=2.46572967.1262995201.1503744350-4158818.1502218306">
            <div class="img">
              <img src="{% static 'img/one-petro-logo.jpg' %}" alt="one-petro-logo" width="100">
            </div>
              <h4 class="tile-caption text-center">Online Paper Library</h4>
            </a>
          </div>

          <div class="padding">
            <div class="resource">
              <a href="http://petrowiki.org/PetroWiki">
              <div class="img">
                <img src="{% static 'img/Petrowiki_logo.png' %}" alt="Petrowiki-logo" width="100">
              </div>
                <h4 class="tile-caption text-center">Wikipedia for Exploration & Production Industry</h4>
              </a>
            </div>
          </div>
        </div>
        <div class="col-sm-12 col-md-4">
          <div class="padding"></div>
          <div class="resource">
            <a href="http://www.energy4me.org">
            <div class="img">
              <img src="{% static 'img/e4m.jpg' %}" alt="Energy4me-logo" width="100">
            </div>
              <h4 class="tile-caption text-center">E & P classroom Education</h4>
            </a>
          </div>

          <div class="padding">
            <div class="resource">
              <a href="http://www.spe.org/jpt/">
              <div class="img">
                <img src="{% static 'img/jpt.png' %}" alt="jpt-logo" width="100">
              </div>
                <h4 class="tile-caption text-center">journal of petroluem technology</h4>
              </a>
            </div>
          </div>
        </div>
        <div class="col-sm-12 col-md-4">
          <div class="padding"></div>
          <div class="resource">
            <a href="http://www.spe.org/hsenow/">
            <div class="img">
              <img src="{% static 'img/hsenow.png' %}" alt="HSE-Now-logo" width="100">
            </div>
              <h4 class="tile-caption text-center">A digital paper for HSSE-SR</h4>
            </a>
          </div>

          <div class="padding">
            <div class="resource">
              <a href="https://webevents.spe.org/">
              <div class="img">
                <img src="{% static 'img/spe-connect.png' %}" alt="spe-connect" width="100">
              </div>
                <h4 class="tile-caption text-center">networking and discussion platform</h4>
              </a>
            </div>
          </div>
        </div>
      </div>
      {% endblock %}
    </div>

    <!--              Vision 
    ================================================== 
    -->
    {% block vision %}
    <div class="row">
      <div class="container tile-body container-wrapper">
        <h3 class="tile-header text-center">Vision</h3>
        <p class="vision-text text-center">SPEOAU Student Chapter aims at providing each affiliate with opportunities for personal and professional development through an amalgamation of events round the year including Distinguished Lectures, Workshops, Soft Skill Development Seminars and a plethora of contests. We strive to provide each and every student member a common platform to showcase their acumen in front of eminent industry veterans and compete with peers. The learning programs are aimed at making student members well acquainted with Reservoir, Production and Drilling Engineering and also get familiar with Health, Safety and Environmental factors of Oil and Gas industry. It also focuses on unconventional energy sources.</p>
      </div>
    </div>
    {% endblock %}
    <!--              Gallery 
    ================================================== 
    -->
    {% block gallery %}
    <div class="row">
      <div class="jumbotron">
        {% for image in gallery %}{% endfor %}
      </div>
    </div>
    {% endblock %}
    <!--              Exco's 
    ================================================== 
    -->
    <footer>
      <p class="pull-right"><a href="#">Back to top</a></p>
      <p>&copy; 2016 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
    </footer>

  </div>

  <script type="text/javascript" src="{% block jqeury %}{% static 'js/jquery.min.js' %}{% endblock %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script type="text/javascript" src="{% block js %}{% static 'js/base.js' %}{% endblock %}"></script>

</body>
</html>

speoau/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block events %}
	<div class="col-sm-12 col-md-6">
		<a href="{% url 'posts:all_event' %}">
			<div class="title-tile">
			  <h3 class="tile-header" style="background-color: #102c4e">Upcoming Events</h3>
			</div>
		</a>
		<div class="events-body" style="padding: 0 20px;">
		{% for event in events %}
		  <h4 class="tile-caption"><a href="{% url 'posts:event_detail' event.pk %}">{{ event.event }}</a></h4>
		  <p class="event-date"><strong>Date:{{event.event_date}}</strong></p>
		  <p class="tile-text">{{event.summary}}</p>
		{% endfor %}
		</div>
	</div>
{% endblock %}  